# Site settings
title: OperaToolkit
email: operatoolkit@gmail.com
description: OperaToolkit is cool stuff made by Lisa, Colin, and Gene
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://operatoolkit.github.io" # the base hostname & protocol for your site
twitter_username: genekogan
github_username:  genekogan

# Build settings
markdown: kramdown
